#! /bin/bash -e
function die() {
   echo "$@" 1>&2
   exit 1
}

if [ -z "$www" ]; then
   www="$HOME/Documents/2019b/2019-2020--HOME/www"
fi

if [ -n "$www" ]; then
   cd "$www"
fi

if [ ! -f ./hugo-server ]; then
   echo "$0: not running in correct directory" 1>&2
   exit 1
fi

# cd $www
i3-msg "workspace 5; append_layout $HOME/.config/i3/layout-www-edit.json"
emacs --title "Site Editor" content/ &
i3-sensible-terminal --title "Hugo Site Generator" -e ./hugo-server &
i3-sensible-terminal --title "Publisher" -e fish &


